services:
  jenkins:
    build:
      context: .
    container_name: cloudforge-jenkins

    restart: unless-stopped

    ports:
      - "8081:8080"
      - "50000:50000"

    environment:
      AWS_PROFILE: cloudforge
      AWS_REGION: eu-central-1

    volumes:
      - jenkins_home:/var/jenkins_home

      # Local development için Mac'teki AWS profilini read-only kullanıyoruz.
      - ${HOME}/.aws:/var/jenkins_home/.aws

volumes:
  jenkins_home:
