name: Security CI

on:
  pull_request:
    paths:
      - "apps/**"
      - "infrastructure/**"
      - ".github/workflows/security-ci.yml"
      - ".tflint.hcl"

  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "infrastructure/**"
      - ".github/workflows/security-ci.yml"
      - ".tflint.hcl"

permissions:
  contents: read

jobs:
  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.0
        with:
          cache: true

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: |
          tflint \
            --recursive \
            --chdir infrastructure/terraform \
            --format compact

  checkov:
    name: Checkov IaC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: |
          checkov \
            -d infrastructure/terraform \
            --framework terraform \
            --soft-fail

  trivy-secrets:
    name: Trivy Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Scan repository
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          severity: HIGH,CRITICAL
          exit-code: "1"

  trivy-iac:
    name: Trivy IaC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Scan Terraform
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: infrastructure/terraform
          severity: HIGH,CRITICAL
          exit-code: "0"

  container-security:
    name: Container Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build demo image
        run: |
          docker build \
            -t cloudforge-demo-app:security-ci \
            apps/demo-app

      - name: Scan image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: cloudforge-demo-app:security-ci
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
